server:
  port: 8087
spring:
  application:
    name: swaggerDemo
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}